<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<script src="SpryAssets/SpryMenuBar.js" type="text/javascript"></script>
<link href="SpryAssets/SpryMenuBarHorizontal.css" rel="stylesheet" type="text/css" />
<link href="SpryAssets/SpryMenuBarVertical.css" rel="stylesheet" type="text/css" />
<style type="text/css">
.FONT {
	color: #CFF;
	font-size: 24px;
	font-weight: bold;
	font-family: Verdana, Geneva, sans-serif;
}
</style>
</head>

<body bgcolor="#5195BA">
<div align="center">
  <table width="1323" height="580" border="2">
<tr>
  <td width="1349" height="500" align="left" valign="top"><table width="1313" height="130">
        <tr>
          <td width="1265" height="100" align="center" valign="bottom" background="IMAGES/TOPBORDER.jpg"><ul id="MenuBar1" class="MenuBarHorizontal">
        </tr>
      </table>
        <marquee behavior="scroll" direction="left"> <font color="YELLOW" face=verdana size='2'><b> *** IF YOU HAVE ANY SUGGESTIONS OR CHANGES ON THIS SITE PLEASE SHARE WITH ANALYSIS WING *** </b></font></marquee> 
        <table width="1307" height="347">
          <tr>
            <td width="214" rowspan="2" valign="top">
              <blockquote>
                <ul class="MenuBarVertical">
          <li><a href="JRMS_NEW_RECORDS_ENTRY_UNIQUENESS_PHP.PHP">JRMS NEW RECORDS ENTRY</a></li>
          <li><a href="JRMS_DATEWISE_SEARCH_UNIQUENESS.HTM">JRMS SEARCH BY RELEASE DATE</a></li>
          <li><a href="JRMS_CIN_SEARCH_UNIQUENESS.HTML">JRMS SEARCH BY CIN NUMBER</a></li>
   <li><a href="JRMS_SEARCH_BY_PRISONERNO_UNIQUENESS.HTM">
JRMS SEARCH BY PRISONER NO</a></li>
          <li><a href="JRMS_SEARCH_UNIQUENESS.HTML">
JRMS SEARCH BY NAME AND UNIQUE ID's</a></li>
          <li><a href="JRMS_UNIQUE_KEY_UPDATE.HTM">
JRMS UNIQUE KEY UPDATATION FORM</a></li>
   <li><a href="mulakath_entry.php">
MULAKATH_ENTRY</a></li>
          </ul>
        <p>&nbsp; </p>
      </blockquote></td>
            <td width="1015" height="24" align="left" valign="top"><p align="center" class="FONT"> JRMS OFFENDER UNIQUING   </p></td>
            <td width="62" rowspan="2">&nbsp;</td>
          </tr>
          <tr>
            <td height="310" align="left" valign="top"><div align="center"><img src="IMAGES/ANALYSIS1.jpg" width="950" height="250" /></div></td>
          </tr>
        </table>
        <p>&nbsp;</p>
    
  <script type="text/javascript">
var MenuBar1 = new Spry.Widget.MenuBar("MenuBar1", {imgDown:"SpryAssets/SpryMenuBarDownHover.gif", imgRight:"SpryAssets/SpryMenuBarRightHover.gif"});
var MenuBar2 = new Spry.Widget.MenuBar("MenuBar2", {imgRight:"SpryAssets/SpryMenuBarRightHover.gif"});
</script>
</body>
</html>
