<?php
$serverName = "CPHYDERABAD1\DAU_HYD_2023";
$connectionInfo = array( "Database"=>"MIGRANT_LABOURS_FORM");
$conn = sqlsrv_connect( $serverName, $connectionInfo );
if( $conn === false ) {
    die( print_r( sqlsrv_errors(), true));
}
$POLICE_STATION=$_POST['POLICE_STATION']; 
$NAME=$_POST['NAME'];     
$FATHER_NAME=$_POST['FATHER_NAME'];     
$AGE=$_POST['AGE'];     
$NATIVE_STATE=$_POST['NATIVE_STATE'];     
$NATIVE_DISTRICT=$_POST['NATIVE_DISTRICT'];     
$PHONE=$_POST['PHONE'];     
$WORK_STATUS=$_POST['WORK_STATUS'];     
$PART_OF_LABOUR_CAMP=$_POST['PART_OF_LABOUR_CAMP'];     
$URGENT=$_POST['URGENT'];     
$PROBLEM_CASES=$_POST['PROBLEM_CASES'];     
$REMARKS=$_POST['REMARKS'];     
$DATE1=$_POST['DATE1'];     

$sql="insert into MIGRANT_LABOURS_FORM.DBO.MIGRANT_LABOUR_TABLE (NAME, FATHER_NAME, AGE, NATIVE_STATE, NATIVE_DISTRICT, PHONE, WORK_STATUS,
PART_OF_LABOUR_CAMP, URGENT, PROBLEM_CASES, REMARKS, DATE1,POLICE_STATION,DIVISION,ZONE,ENTRY_DATE) 
values('$NAME','$FATHER_NAME','$AGE','$NATIVE_STATE', '$NATIVE_DISTRICT','$PHONE', '$WORK_STATUS','$PART_OF_LABOUR_CAMP', '$URGENT', '$PROBLEM_CASES', '$REMARKS', '$DATE1','$POLICE_STATION',
(SELECT DISTINCT DIVISION FROM PS_NAMES WHERE PS='$POLICE_STATION'),(SELECT DISTINCT ZONE FROM PS_NAMES WHERE PS='$POLICE_STATION'),GETDATE())";
if(!sqlsrv_query($conn,$sql))
{
echo "not inserted";
}
else
{
echo "inserted";
}
?>