<?php
$serverName = "CPHYDERABAD1\DAU_HYD_2023";
$connectionInfo = array( "Database"=>"JRMS");
$conn = sqlsrv_connect( $serverName, $connectionInfo );
if( $conn === false ) {
    die( print_r( sqlsrv_errors(), true));
}
$JAIL_NAME=$_POST['JAIL_NAME']; 
$PRISONER_NO=$_POST['PRISONER_NO'];
$PRISONER_NAME=$_POST['PRISONER_NAME'];
$PRISONER_FATHER_NAME=$_POST['PRISONER_FATHER_NAME'];
$VISITOR_NAME =$_POST['VISITOR_NAME']; 
$VISITOR_PHONE_NO =$_POST['VISITOR_PHONE_NO']; 
$VISITOR_ID=$_POST['VISITOR_ID'];
$VISITOR_NAME_2 =$_POST['VISITOR_NAME_2'];
$VISITOR_PHONE_NO_2 =$_POST['VISITOR_PHONE_NO_2']; 
$VISITOR_ID_2=$_POST['VISITOR_ID_2']; 
$VISITOR_NAME_3 =$_POST['VISITOR_NAME_3']; 
$VISITOR_PHONE_NO_3 =$_POST['VISITOR_PHONE_NO_3']; 
$VISITOR_ID_3=$_POST['VISITOR_ID_3'];
$VISITOR_NAME_4 =$_POST['VISITOR_NAME_4'];  
$VISITOR_PHONE_NO_4 =$_POST['VISITOR_PHONE_NO_4']; 
$VISITOR_ID_4=$_POST['VISITOR_ID_4'];
$DATE_OF_MULAKATH=$_POST['DATE'];
$CRIME_NO =$_POST['CRIME_NO']; 
$YEAR =$_POST['YEAR'];
$POLICE_STATION =$_POST['POLICE_STATION']; 
$sql="insert into JRMS.dbo.MULAKATH_ENTRY 
(JAIL_NAME, PRISONER_NO, PRISONER_NAME, PRISONER_FATHER_NAME, VISITOR_NAME, VISITOR_PHONE_NO, 
VISITOR_ID,VISITOR_NAME_2,VISITOR_PHONE_NO_2, 
VISITOR_ID_2,VISITOR_NAME_3,VISITOR_PHONE_NO_3, 
VISITOR_ID_3,VISITOR_NAME_4,VISITOR_PHONE_NO_4, 
VISITOR_ID_4,DATE_OF_MULAKATH,CRIME_NO, YEAR, POLICE_STATION)
values('$JAIL_NAME','$PRISONER_NO','$PRISONER_NAME','$PRISONER_FATHER_NAME',
'$VISITOR_NAME','$VISITOR_PHONE_NO','$VISITOR_ID','$VISITOR_NAME_2','$VISITOR_PHONE_NO_2','$VISITOR_ID_2','$VISITOR_NAME_3','$VISITOR_PHONE_NO_3','$VISITOR_ID_3','$VISITOR_NAME_4','$VISITOR_PHONE_NO_4','$VISITOR_ID_4','$DATE_OF_MULAKATH','$CRIME_NO','$YEAR','$POLICE_STATION')";
if(!sqlsrv_query($conn,$sql))
{
echo "not inserted";
}
else
{
echo "inserted";
}
header("refresh:30; url=mulakath_entry.php");
?>