<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Untitled Document</title>
<script src="../assets/spry/sprymenubar.js" type="text/javascript"></script>
<link href="../assets/spry/sprymenubarhorizontal.css" rel="stylesheet" type="text/css" />
<link href="../assets/spry/sprymenubarvertical.css" rel="stylesheet" type="text/css" />
<style type="text/css">
.FONT {
	color: #CFF;
	font-size: 24px;
	font-weight: bold;
	font-family: Verdana, Geneva, sans-serif;
}
</style>
</head>

<body bgcolor="#5195BA">
<div align="center">
  <table width="1323" height="603" border="2">
<tr>
  <td width="1349" height="595" align="left" valign="top"><table width="1313" height="148">
        <tr>
          <td width="1265" height="134" align="center" valign="bottom" background="../assets/images/topborder.jpg"><ul id="MenuBar1" class="MenuBarHorizontal">
            <li><a href="HOME_IR.html">Home</a>              </li>
            <li><a href="IRREPORT.html">IRREPORT</a></li>
            <li><a href="FAMILY_HISTORY.html">FAMILY HISTORY</a></li>
            <li><a href="HOME_IR.html" class="MenuBarItemSubmenu">CRIME DETAILS</a>
             <ul>
                <li><a href="OFFENCE_DETAILS.HTML">OFFENCE DETAILS</a></li>
                <li><a href="PREVIOUS_OFFENCE_DETAILS.HTML">PREVIOUS OFFENCE DETAILS</a></li>
              </ul>
              </li>
            <li><a href="LOCAL_CONTACTS.html">LOCAL CONTACTS</a></li>
            <li><a href="RELATION_WITH_OTHER_ASSOCIATES_AND_GANGS.html">GANGS/ASSOCIATES</a></li>
            <li><a href="DISPOSAL_OF_PROPERTY.HTML">PROPERTY DETAILS</a></li>
            <li><a href="BRIEF_FACTS.HTML">BRIEF FACTS</a></li>
            <li><a href="IMAGE_LIST.HTML">IMAGE</a></li>
          </ul></td>
        </tr>
      </table>
        <marquee behavior="scroll" direction="left"> <font color="YELLOW" face=verdana size='2'><b> *** IF YOU HAVE ANY SUGGESTIONS OR CHANGES ON THIS SITE PLEASE SHARE WITH ANALYSIS WING *** </b></font></marquee> 
        <table width="1307" height="347">
          <tr>
            <td width="214" rowspan="2" valign="top">
              <blockquote>
                <ul class="MenuBarVertical">
          <li><a href="IRREPORT.HTML">IRREPORT</a></li>
          <li><a href="FAMILY_HISTORY.HTML">FAMILY HISTORY</a>            </li>
          <li><a href="OFFENCE_DETAILS.HTML">OFFENCE DETAILS</a></li>
          <li><a href="PREVIOUS_OFFENCE_DETAILS.HTML">PREVIOUS OFFENCE DETAILS</a></li>
          <li><a href="LOCAL_CONTACTS.HTML">LOCAL CONTACTS</a></li>
          <li><a href="RELATION_WITH_OTHER_ASSOCIATES_AND_GANGS.HTML">GANGS/ASSOCIATES</a>            </li>
          <li><a href="DISPOSAL_OF_PROPERTY.HTML">PROPERTY</a></li>
          <li><a href="BRIEF_FACTS.HTML">BRIEF FACTS</a></li>
          <li><a href="IMAGE_LIST.HTML">IMAGE</a></li>          
        </ul>
        <p>&nbsp; </p>
      </blockquote></td>
            <td width="1015" height="24" align="left" valign="top"><p align="center" class="FONT"> INTERROGATION REPORTS </p></td>
            <td width="62" rowspan="2">&nbsp;</td>
          </tr>
          <tr>
            <td height="310" align="left" valign="top"><div align="center"><img src="../assets/images/analysis1.jpg" width="950" height="250" /></div></td>
          </tr>
        </table>
        <p>&nbsp;</p>
    
  <script type="text/javascript">
var MenuBar1 = new Spry.Widget.MenuBar("MenuBar1", {imgDown:"../assets/spry/sprymenubardownhover.gif", imgRight:"../assets/spry/sprymenubarrighthover.gif"});
var MenuBar2 = new Spry.Widget.MenuBar("MenuBar2", {imgRight:"../assets/spry/sprymenubarrighthover.gif"});
</script>
</body>
</html>
