<?php
$serverName = "USER-HP";
$connectionInfo = array( "Database"=>"forms");
$conn = sqlsrv_connect( $serverName, $connectionInfo );
if( $conn === false ) {
    die( print_r( sqlsrv_errors(), true));
}
$IRKEY=$_POST['IRKEY'];
$PERIOD_OF_OFFENCE=$_POST['PERIOD_OF_OFFENCE'];
$REGULAR_RESIDENCE=$_POST['REGULAR_RESIDENCE'];
$PREPARATION_OF_OFFENCE=$_POST['PREPARATION_OF_OFFENCE'];
$AFTER_OFFENCE=$_POST['AFTER_OFFENCE'];
$INDULGANCE_BEFORE_OFFENCE=$_POST['INDULGANCE_BEFORE_OFFENCE'];
$CRIME_HEAD=$_POST['CRIME_HEAD'];
$SUB_TYPE=$_POST['SUB_TYPE'];
$MO=$_POST['MO'];
$DATE_OF_ARREST=$_POST['DATE'];
$PLACE_OF_ARREST=$_POST['PLACE_OF_ARREST'];
$SUB_DIVISION=$_POST['SUB_DIVISION'];
$DISTRICT_OR_UNIT=$_POST['DISTRICT_OR_UNIT'];
$ARRESTED_BY=$_POST['ARRESTED_BY'];
$INTERROGATED_BY=$_POST['INTERROGATED_BY'];
$OTHERS_WHO_CAN_IDENTIFY=$_POST['OTHERS_WHO_CAN_IDENTIFY'];
$CRIME_NO=$_POST['CRIME_NO'];
$YEAR=$_POST['YEAR'];
$SEC_OF_LAW=$_POST['SEC_OF_LAW'];
$POLICE_STATION=$_POST['POLICE_STATION'];
$sql="insert into FORMS.dbo.OFFENCE_DETAILS (IRKEY, PERIOD_OF_OFFENCE, REGULAR_RESIDENCE, PREPARATION_OF_OFFENCE, AFTER_OFFENCE, 
INDULGANCE_BEFORE_OFFENCE, CRIME_HEAD, SUB_TYPE, MO, DATE_OF_ARREST, PLACE_OF_ARREST, 
SUB_DIVISION, DISTRICT_OR_UNIT, ARRESTED_BY, INTERROGATED_BY, OTHERS_WHO_CAN_IDENTIFY, 
CRIME_NO, YEAR, SEC_OF_LAW, POLICE_STATION) values('$IRKEY','$PERIOD_OF_OFFENCE',
'$REGULAR_RESIDENCE','$PREPARATION_OF_OFFENCE','$AFTER_OFFENCE','$INDULGANCE_BEFORE_OFFENCE',
'$CRIME_HEAD','$SUB_TYPE','$MO','$DATE_OF_ARREST','$PLACE_OF_ARREST','$SUB_DIVISION','$DISTRICT_OR_UNIT',
'$ARRESTED_BY','$INTERROGATED_BY','$OTHERS_WHO_CAN_IDENTIFY','$CRIME_NO','$YEAR','$SEC_OF_LAW','$POLICE_STATION')";
if(!sqlsrv_query($conn,$sql))
{
echo "not inserted";
}
else
{
echo "inserted";
}
header("refresh:30; url=OFFENCE_DETAILS.html");
?>